/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package form;

import communication.Communication;
import domain.Masinovodja;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class FrmIzmeniMasinovodju extends javax.swing.JDialog {

    /**
     * Creates new form FrmIzmeniMasinovodju
     */
    public FrmIzmeniMasinovodju(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        pripremiMasinovodje();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtMasinovodjaID = new javax.swing.JTextField();
        jTxtIme = new javax.swing.JTextField();
        jTxtPrezime = new javax.swing.JTextField();
        jTxtRadniStaž = new javax.swing.JTextField();
        btnIzmeniMasinovodju = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cbMasinovodje = new javax.swing.JComboBox<>();
        jTxtDatumRodjenja = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Izmeni mašinovođu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setText("Ime");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("MašinovođaID");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Prezime");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("Datum rođenja");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("Radni staž");

        btnIzmeniMasinovodju.setText("Izmeni");
        btnIzmeniMasinovodju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniMasinovodjuActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setText("Izaberi mašinovođu");

        cbMasinovodje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMasinovodjeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(btnIzmeniMasinovodju, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbMasinovodje, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtIme)
                            .addComponent(jTxtPrezime)
                            .addComponent(jTxtRadniStaž)
                            .addComponent(jTxtMasinovodjaID)
                            .addComponent(jTxtDatumRodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbMasinovodje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtMasinovodjaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTxtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTxtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtDatumRodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTxtRadniStaž, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnIzmeniMasinovodju))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzmeniMasinovodjuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniMasinovodjuActionPerformed
       String radniStaz= jTxtRadniStaž.getText();
        int radniStazInt = 0;
        if(radniStaz.length() == 0){
            JOptionPane.showMessageDialog(this, "Morate uneti radni staz masinovodje!");
            return;
        }
        try {
            radniStazInt = Integer.parseInt(radniStaz);
            Masinovodja masinovodja = (Masinovodja) cbMasinovodje.getSelectedItem();
            masinovodja.setRadniStaz(radniStazInt);
            Communication.getInstance().zapamtiMasinovodju(masinovodja); 
            JOptionPane.showMessageDialog(this, "Uspenso izmenjen radni staz masinovodje");
            cbMasinovodje.removeAllItems();
            pripremiMasinovodje();
        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this, "Radni staz masinovodje mora biti broj");
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(this, "Greska pri izmeni radnog staza masinovodje!","Greska",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnIzmeniMasinovodjuActionPerformed

    private void cbMasinovodjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMasinovodjeActionPerformed
        // TODO add your handling code here:
         Masinovodja masinovodja = (Masinovodja)cbMasinovodje.getSelectedItem();
        if(masinovodja!=null){
        jTxtRadniStaž.setEnabled(true);
        jTxtMasinovodjaID.setText(String.valueOf(masinovodja.getMasinovodjaID()));
        jTxtIme.setText(masinovodja.getIme());
        jTxtPrezime.setText(masinovodja.getPrezime());
        jTxtDatumRodjenja.setText(masinovodja.getDatumRodjenja()+"");
        jTxtRadniStaž.setText(masinovodja.getRadniStaz()+"");
        }
    }//GEN-LAST:event_cbMasinovodjeActionPerformed
    
    private void cbMasinovodjeMouseClicked(java.awt.event.MouseEvent evt) {                                     
        Masinovodja masinovodja = (Masinovodja)cbMasinovodje.getSelectedItem();
        if(masinovodja!=null){
        jTxtRadniStaž.setEnabled(true);
        jTxtMasinovodjaID.setText(String.valueOf(masinovodja.getMasinovodjaID()));
        jTxtIme.setText(masinovodja.getIme());
        jTxtPrezime.setText(masinovodja.getPrezime());
        jTxtDatumRodjenja.setText(masinovodja.getDatumRodjenja()+"");
        jTxtRadniStaž.setText(masinovodja.getRadniStaz()+"");
        }
    }                           
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeniMasinovodju;
    private javax.swing.JComboBox<Masinovodja> cbMasinovodje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtDatumRodjenja;
    private javax.swing.JTextField jTxtIme;
    private javax.swing.JTextField jTxtMasinovodjaID;
    private javax.swing.JTextField jTxtPrezime;
    private javax.swing.JTextField jTxtRadniStaž;
    // End of variables declaration//GEN-END:variables
  private void pripremiMasinovodje() {
       try {
            List<Masinovodja> masinovodje = Communication.getInstance().ucitajListuMasinovodja();
            for (Masinovodja masinovodja : masinovodje) {
            cbMasinovodje.addItem(masinovodja);
            }
            cbMasinovodje.setEnabled(true);
//            tbRadniStaz.setEnabled(true);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
