/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JLabel;
import threads.DateTimeThread;

/**
 *
 * @author User
 */
public class FrmMain extends javax.swing.JFrame {
    String username;
    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        setLocationRelativeTo(null);
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setTitle("Pracenje rada zeleznice");
//        setTime();
    }
    public FrmMain(String korisnik){
        username = korisnik;
        setLocationRelativeTo(null);
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setTitle("Pracenje rada zeleznice");
        setTime();
        prepare();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDobrodosli = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblKorisnik = new javax.swing.JLabel();
        lblDatumVreme = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jFrmMasinovodja = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblDobrodosli.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblDobrodosli.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDobrodosli.setText("Dobro došli!");
        lblDobrodosli.setToolTipText("");
        lblDobrodosli.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setText("Datum");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setText("Ulogovani koristnik:");

        lblKorisnik.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N

        lblDatumVreme.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N

        jMenu1.setText("Mašinovođa");

        jFrmMasinovodja.setText("Forma mašinovođa");
        jFrmMasinovodja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFrmMasinovodjaActionPerformed(evt);
            }
        });
        jMenu1.add(jFrmMasinovodja);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Voz");

        jMenuItem1.setText("Forma voz");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Vožnja");

        jMenuItem2.setText("Forma vožnja");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addComponent(lblKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(lblDatumVreme, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(357, 357, 357)
                .addComponent(lblDobrodosli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(357, 357, 357))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDatumVreme, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(146, 146, 146)
                .addComponent(lblDobrodosli, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addGap(163, 163, 163))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFrmMasinovodjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFrmMasinovodjaActionPerformed
           // TODO add your handling code here:
           new FrmMasinovodja(new JFrame(), true).setVisible(true);
    }//GEN-LAST:event_jFrmMasinovodjaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new FrmVoz(new JFrame(), true).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         new FrmVoznja(new JFrame(), true).setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jFrmMasinovodja;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel lblDatumVreme;
    private javax.swing.JLabel lblDobrodosli;
    private javax.swing.JLabel lblKorisnik;
    // End of variables declaration//GEN-END:variables
    private void setTime() {
        DateTimeThread dateTime= new DateTimeThread(lblDatumVreme);
        dateTime.start();
    }
    private void prepare(){
        lblKorisnik.setText(username);
//        Dimension dimenzijeEkrana = Toolkit.getDefaultToolkit().getScreenSize();
//        int sirinaEkrana = dimenzijeEkrana.width;
//        int visinaEkrana = dimenzijeEkrana.height;
//        int sirinaProzora = this.getWidth();
//        int visinaProzora = this.getHeight();
//        int x = (sirinaEkrana - sirinaProzora) / 2;
//        int y = (visinaEkrana - visinaProzora) / 2;
//        lblDobrodosli.setHorizontalAlignment(JLabel.CENTER);
//        lblDobrodosli.setLocation(x, y);

        
    }
}
