/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package form;

import communication.Communication;
import domain.DestinacijaVoznje;
import domain.Mesto;
import domain.Voznja;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.TableModel;
import tables.VoznjaTableModel;

/**
 *
 * @author User
 */
public class FrmVoznja extends javax.swing.JDialog {

    /**
     * Creates new form FrmVoznja
     */
    public FrmVoznja(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Voznja");
        setLocationRelativeTo(null);
        prepareComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVoznje = new javax.swing.JTable();
        btnKreirajVoznju = new javax.swing.JButton();
        btnIzmeniVoznju = new javax.swing.JButton();
        btnPretrazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vožnje", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 18))); // NOI18N

        jTableVoznje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableVoznje);

        btnKreirajVoznju.setText("Dodaj voznju");
        btnKreirajVoznju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajVoznjuActionPerformed(evt);
            }
        });

        btnIzmeniVoznju.setText("Izmeni voznju");
        btnIzmeniVoznju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniVoznjuActionPerformed(evt);
            }
        });

        btnPretrazi.setText("Pretrazi voznje");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnKreirajVoznju, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138)
                        .addComponent(btnIzmeniVoznju, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154)
                        .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKreirajVoznju)
                    .addComponent(btnIzmeniVoznju)
                    .addComponent(btnPretrazi))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKreirajVoznjuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajVoznjuActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new FrmKreirajVoznju(new JFrame(), true).setVisible(true);
    }//GEN-LAST:event_btnKreirajVoznjuActionPerformed

    private void btnIzmeniVoznjuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniVoznjuActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new FrmIzmeniVoznju(new JFrame(), true).setVisible(true);
    }//GEN-LAST:event_btnIzmeniVoznjuActionPerformed

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new FrmPretraziVoznju(new JFrame(), true).setVisible(true);
    }//GEN-LAST:event_btnPretraziActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeniVoznju;
    private javax.swing.JButton btnKreirajVoznju;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVoznje;
    // End of variables declaration//GEN-END:variables

    private void prepareComponents() {
        try {
            List<Voznja> voznje = Communication.getInstance().ucitajListuVoznji();
            List<Mesto> mesta = kreirajMestaPoRasporeduVoznji(voznje);
            
            TableModel model = new VoznjaTableModel(voznje, mesta);
            jTableVoznje.setModel(model);

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    private List<Mesto> ucitajListuMesta() {
        try {
            return (List<Mesto>) Communication.getInstance().ucitajListuMesta();
        } catch (Exception ex) {
            ex.printStackTrace();
            return null;
        }
    }

    private List<DestinacijaVoznje> ucitajListuDestinacija() {
        try {
            return (List<DestinacijaVoznje>) Communication.getInstance().UcitajListuDestinacija();
        } catch (Exception ex) {
            ex.printStackTrace();
            return null;
        }
    }

    private List<Mesto> kreirajMestaPoRasporeduVoznji(List<Voznja> voznje) {
        List<Mesto> mesta = new ArrayList<>();
        for (Voznja voznja : voznje) {
            if (getMestoFromDestinacija(voznja.getVoznjaID()) != null) {
                mesta.add(getMestoFromDestinacija(voznja.getVoznjaID()));
            }
        }
        return mesta;
    }

    private Mesto getMestoFromDestinacija(long voznjaID) {
        List<DestinacijaVoznje> destinacije = ucitajListuDestinacija();
        for (DestinacijaVoznje destinacijaVoznje : destinacije) {
            if (destinacijaVoznje.getVoznja().getVoznjaID() == voznjaID) {
                Mesto mesto = destinacijaVoznje.getMesto();
                mesto.setNaziv(getNazivMesta(mesto.getPostanskiBroj()));
                return mesto;
            }
        }
        return null;
    }

    private String getNazivMesta(long postanskiBroj) {
        List<Mesto> mesta = ucitajListuMesta();
        for (Mesto mesto : mesta) {
            if (mesto.getPostanskiBroj()== postanskiBroj) {
                return mesto.getNaziv();
            }
        }
        return null;
    }
}
